// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElUpload: typeof import('element-plus/es')['ElUpload']
    ImgUpload: typeof import('./src/components/img-upload/img-upload.vue')['default']
    MAvatar: typeof import('./src/components/avatar/MAvatar.vue')['default']
    MCard: typeof import('./src/components/card/MCard.vue')['default']
    MDropdown: typeof import('./src/components/dropdown/MDropdown.vue')['default']
    Message: typeof import('./src/components/Message/Message.vue')['default']
    MGird: typeof import('./src/components/gird/MGird.vue')['default']
    MSlider: typeof import('./src/components/slider/MSlider.vue')['default']
    Mytest: typeof import('./src/components/mytest/index.vue')['default']
    QuikPick: typeof import('./src/components/quik-pick/quik-pick.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBar: typeof import('./src/components/search/SearchBar.vue')['default']
    SearchBox: typeof import('./src/components/SearchBox/SearchBox.vue')['default']
    VirtualList: typeof import('./src/components/virtualList/VirtualList.vue')['default']
  }
}
