// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElRow: typeof import('element-plus/es')['ElRow']
    MAvatar: typeof import('./src/components/Avatar/MAvatar.vue')['default']
    MCard: typeof import('./src/components/Card/MCard.vue')['default']
    MDropdown: typeof import('./src/components/DropDown/MDropdown.vue')['default']
    Message: typeof import('./src/components/Message/Message.vue')['default']
    MSlider: typeof import('./src/components/Slider/MSlider.vue')['default']
    Mytest: typeof import('./src/components/mytest/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SearchBar: typeof import('./src/components/Search/SearchBar.vue')['default']
    SearchBox: typeof import('./src/components/SearchBox/SearchBox.vue')['default']
    Testvm: typeof import('./src/components/testvm.vue')['default']
    VirtualList: typeof import('./src/components/VirtualList/VirtualList.vue')['default']
  }
}
